
package prodENV;

import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.plaf.basic.BasicButtonUI;

/**
 *
 * @author user
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        JButton[] btns = {jButton1, jButton2, jButton3, jButton4, jButton5, jButton6};
        for (JButton btn : btns) {
            btn.setBackground(new Color(21, 25, 28));
            btn.setUI(new BasicButtonUI());
            btn.addMouseListener(new MouseListener(){
                @Override
                public void mouseClicked(MouseEvent e) {
                    for (JButton button : btns) {
                    if (button == btn) {
                        button.setBackground(new Color(123, 122, 129));
                    } else {
                        button.setBackground(new Color(21, 25, 28));
                    }
                }
                }

                @Override
                public void mousePressed(MouseEvent e) {
                       btn.setBackground(new Color(21, 25, 28));
                }

                @Override
                public void mouseReleased(MouseEvent e) {
                    
                }

                @Override
                public void mouseEntered(MouseEvent e) {
                    
                }

                @Override
                public void mouseExited(MouseEvent e) {
                     
                }
            
            });
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRoot = new javax.swing.JPanel();
        pnlSlide = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        pnlCenter = new javax.swing.JPanel();
        pnlCtop = new javax.swing.JPanel();
        pnlCCenter = new javax.swing.JPanel();
        pnlCBottom = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 550));

        pnlRoot.setLayout(new java.awt.BorderLayout());

        pnlSlide.setBackground(new java.awt.Color(21, 25, 28));
        pnlSlide.setPreferredSize(new java.awt.Dimension(53, 550));
        pnlSlide.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 7, 20));

        jPanel1.setBackground(new java.awt.Color(21, 25, 28));
        jPanel1.setPreferredSize(new java.awt.Dimension(40, 100));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 25));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prodENV/Icons/windows.png"))); // NOI18N
        jButton6.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel1.add(jButton6);

        pnlSlide.add(jPanel1);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\LocalGIT\\TestCRUD\\src\\prodENV\\Icons\\home (1).png")); // NOI18N
        jButton1.setPreferredSize(new java.awt.Dimension(55, 20));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnlSlide.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prodENV/Icons/hula-hoop.png"))); // NOI18N
        jButton2.setPreferredSize(new java.awt.Dimension(55, 20));
        pnlSlide.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prodENV/Icons/Document.png"))); // NOI18N
        jButton3.setPreferredSize(new java.awt.Dimension(55, 20));
        pnlSlide.add(jButton3);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prodENV/Icons/speedometer.png"))); // NOI18N
        jButton4.setPreferredSize(new java.awt.Dimension(55, 20));
        pnlSlide.add(jButton4);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prodENV/Icons/paragraph.png"))); // NOI18N
        jButton5.setPreferredSize(new java.awt.Dimension(55, 20));
        pnlSlide.add(jButton5);

        pnlRoot.add(pnlSlide, java.awt.BorderLayout.WEST);

        pnlCenter.setBackground(new java.awt.Color(34, 40, 44));
        pnlCenter.setPreferredSize(new java.awt.Dimension(847, 550));
        pnlCenter.setLayout(new java.awt.BorderLayout());

        pnlCtop.setBackground(new java.awt.Color(34, 40, 44));
        pnlCtop.setPreferredSize(new java.awt.Dimension(0, 30));

        javax.swing.GroupLayout pnlCtopLayout = new javax.swing.GroupLayout(pnlCtop);
        pnlCtop.setLayout(pnlCtopLayout);
        pnlCtopLayout.setHorizontalGroup(
            pnlCtopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlCtopLayout.setVerticalGroup(
            pnlCtopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlCenter.add(pnlCtop, java.awt.BorderLayout.NORTH);

        pnlCCenter.setBackground(new java.awt.Color(34, 40, 44));

        javax.swing.GroupLayout pnlCCenterLayout = new javax.swing.GroupLayout(pnlCCenter);
        pnlCCenter.setLayout(pnlCCenterLayout);
        pnlCCenterLayout.setHorizontalGroup(
            pnlCCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1021, Short.MAX_VALUE)
        );
        pnlCCenterLayout.setVerticalGroup(
            pnlCCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 344, Short.MAX_VALUE)
        );

        pnlCenter.add(pnlCCenter, java.awt.BorderLayout.CENTER);

        pnlCBottom.setBackground(new java.awt.Color(34, 40, 44));
        pnlCBottom.setPreferredSize(new java.awt.Dimension(0, 30));

        javax.swing.GroupLayout pnlCBottomLayout = new javax.swing.GroupLayout(pnlCBottom);
        pnlCBottom.setLayout(pnlCBottomLayout);
        pnlCBottomLayout.setHorizontalGroup(
            pnlCBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlCBottomLayout.setVerticalGroup(
            pnlCBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlCenter.add(pnlCBottom, java.awt.BorderLayout.SOUTH);

        pnlRoot.add(pnlCenter, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlRoot, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlCBottom;
    private javax.swing.JPanel pnlCCenter;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlCtop;
    private javax.swing.JPanel pnlRoot;
    private javax.swing.JPanel pnlSlide;
    // End of variables declaration//GEN-END:variables
}
